modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "WTFPL"

[[mods]]
modId = "totemofrevival"
version = "${version}"
displayName = "Totem Of Revival"
authors = "SSBlur"
description = '''
Bring your buddies back in hardcore! Probably!
'''
#logoFile = ""

[[dependencies.totemofrevival]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totemofrevival]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.totemofrevival]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"